model: weights/pretrained/yolov8s.pt
data: configs/rm_armor.yaml

epochs: 30
patience: 15
imgsz: 640
batch: 16
device: 0
workers: 8

project: logs/train
name: yolov8s_baseline
exist_ok: false

pretrained: true
optimizer: auto
seed: 42
deterministic: true
cache: false
amp: true
cos_lr: false
close_mosaic: 10

save: true
save_period: 10
plots: true
fraction: 1.0
